a=10
b=2.4
c="snehal"
d=True
e=[1,2,3,4]
f=(1,2,3,4)
g={"name":"snehal","age":22}
h=None
i=2+3j
k=bytearray([1,2,3,4])
l=bytes([1,2,3,4])
m=frozenset([1,2,3,4])
print(type(a),a)
print(type(b),b)
print(type(c),c)
print(type(d),d)
print(type(e),e)
print(type(f),f)
print(type(g),g)
print(type(h),h)
print(type(i),i)
print(type(k),k)
print(type(l),l)
print(type(m),m)