book1=input("enter text of book 1: ").lower().split()
book2=input("enter text of book 2: ").lower().split()
set1=set(book1)
set2=set(book2)
print("unique words in book 1:",set1)
print("unique words in book 2:",set2)
print("common words:",set1&set2)
print("words only in book 1:",set1-set2)
print("words only in book 2:",set2-set1)
print("total unique words:",len(set1|set2))