import numpy as np
b=np.array([[1,2,3],[4,5,6]])
c=np.array([[2,3,4],[7,8,9]])

print(b,"\n")
print(c)
print("Addition")
print(b+c)
print("substraction")
print(b-c)
print("Multiplication")
print(b*c)
print("Division")
print(b/c)
print("Exponentition of matrix b")
print(b**2)
print("exponentition of matix c")
print(c**2)
print("transpose of mtrix b")
result=np.transpose(b)
print(result)